apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ngu5rnvr3-go 
  janus-idp.io/tekton: ngu5rnvr3-go
  backstage.io/kubernetes-id: ngu5rnvr3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ngu5rnvr3-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml